### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by ohmree** [EvilCorpIncorporated/studylog#15]
We should implement login, maybe using github oauth.  
Edgedb has built-in features for achieving this but we still need to write the auth code ourselves.  
[This tutorial](https://www.edgedb.com/docs/guides/tutorials/phoenix_github_oauth) might be useful for figuring out the schema part of this feature, while for the js side we could probably use any package we want (ideally something with nuxt integration that also supports non-nuxt usage like `trpc-nuxt` which we currently use).

[The documentation for policies and globals](https://www.edgedb.com/docs/guides/tutorials/phoenix_github_oauth) might also be of use here, although it might pertain more to backendless (supabase-like) usage where the browser interacts directly with the db so there's no backend layer that can limit access to resources.

**Comment by Galz648** [comment]
login is not part of the v1 roadmap, and it is not an essential feature. 
login will be implemented in the next iteration of this project.
since local storage is not cleared on extension update, we could use the unique ids of the users and relate it to their emails (once we implement login)
